// used https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md
// as a reference for the emoji list
const emoji_to_unicode = {
  // Face Smiling
  grinning: "😀",
  smiley: "😃",
  smile: "😄",
  grin: "😁",
  laughing: "😆",
  satisfied: "😆",
  sweat_smile: "😅",
  rofl: "🤣",
  joy: "😂",
  slightly_smiling_face: "🙂",
  upside_down_face: "🙃",
  wink: "😉",
  blush: "😊",
  innocent: "😇",

  // Face Affection
  smiling_face_with_three_hearts: "🥰",
  heart_eyes: "😍",
  star_struck: "🤩",
  kissing_heart: "😘",
  kissing: "😗",
  relaxed: "☺️",
  kissing_closed_eyes: "😚",
  kissing_smiling_eyes: "😙",
  smiling_face_with_tear: "🥲",

  // Face Tongue
  yum: "😋",
  stuck_out_tongue: "😛",
  stuck_out_tongue_winking_eye: "😜",
  zany: "🤪",
  zany_face: "🤪",
  stuck_out_tongue_closed_eyes: "😝",
  money_mouth_face: "🤑",

  // Face Hand
  hugs: "🤗",
  hugging: "🤗",
  hand_over_mouth: "🤭",
  shushing_face: "🤫",
  thinking: "🤔",

  // Face Neutral Skeptical
  zipper_mouth: "🤐",
  zipper_mouth_face: "🤐",
  raised_eyebrow: "🤨",
  neutral_face: "😐",
  expressionless: "😑",
  no_mouth: "😶",
  face_in_clouds: "😶",
  smirk: "😏",
  unamused: "😒",
  roll_eyes: "🙄",
  grimacing: "😬",
  face_exhaling: "😮‍💨",
  lying_face: "🤥",

  // Face Sleepy
  relieved: "😌",
  pensive: "😔",
  sleepy: "😪",
  drooling_face: "🤤",
  sleeping: "😴",

  // Face Unwell
  mask: "😷",
  face_with_thermometer: "🤒",
  face_with_head_bandage: "🤕",
  nauseated_face: "🤢",
  vomiting_face: "🤮",
  sneezing_face: "🤧",
  hot_face: "🥵",
  cold_face: "🥶",
  woozy_face: "🥴",
  dizzy_face: "😵",
  face_with_spiral_eyes: "😵‍💫",
  exploding_head: "🤯",

  // Face Hat
  cowboy: "🤠",
  cowboy_hat_face: "🤠",
  partying_face: "🥳",
  disguised_face: "🥸",

  // Face Glasses,
  sunglasses: "😎",
  nerd: "🤓",
  nerd_face: "🤓",
  monocle: "🧐",
  monocle_face: "🧐",

  // Face Concerned
  confused: "😕",
  worried: "😟",
  slightly_frowning_face: "🙁",
  slightly_frowning: "🙁",
  frowning_face: "☹️",
  open_mouth: "😮",
  hushed: "😯",
  astonished: "😲",
  flushed: "😳",
  pleading: "🥺",
  pleading_face: "🥺",
  frowning: "😦",
  anguished: "😧",
  fearful: "😨",
  cold_sweat: "😰",
  disappointed_relieved: "😥",
  cry: "😢",
  sob: "😭",
  scream: "😱",
  confounded: "😖",
  persevere: "😣",
  disappointed: "😞",
  sweat: "😓",
  weary: "😩",
  tired_face: "😫",
  yawning_face: "🥱",

  // Face Negative
  triumph: "😤",
  pout: "😡",
  rage: "😡",
  angry: "😠",
  cursing: "🤬",
  cursing_face: "🤬",
  smiling_imp: "😈",
  imp: "👿",
  skull: "💀",
  skull_and_crossbones: "☠️",

  // Face Costume
  hankey: "💩",
  poop: "💩",
  shit: "💩",
  clown_face: "🤡",
  japanese_ogre: "👹",
  japanese_goblin: "👺",
  ghost: "👻",
  alien: "👽",
  space_invader: "👾",
  robot: "🤖",

  // Cat Face
  smiley_cat: "😺",
  smile_cat: "😸",
  joy_cat: "😹",
  heart_eyes_cat: "😻",
  smirk_cat: "😼",
  kissing_cat: "😽",
  scream_cat: "🙀",
  crying_cat_face: "😿",
  pouting_cat: "😾",

  // Monkey Face
  see_no_evil: "🙈",
  hear_no_evil: "🙉",
  speak_no_evil: "🙊",

  // Heart
  love_letter: "💌",
  cupid: "💘",
  gift_heart: "💝",
  sparkling_heart: "💖",
  heartpulse: "💗",
  heartbeat: "💓",
  revolving_hearts: "💞",
  two_hearts: "💕",
  heart_decoration: "💟",
  heart_exclamation: "❣️",
  heavy_heart_exclamation: "❣️",
  broken_heart: "💔",
  heart_on_fire: "❤️‍🔥",
  mending_heart: "❤️‍🩹",
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  brown_heart: "🤎",
  black_heart: "🖤",
  white_heart: "🤍",

  // Emotion
  kiss: "💋",
  100: "💯",
  anger: "💢",
  boom: "💥",
  collision: "💥",
  dizzy: "💫",
  sweat_drops: "💦",
  dash: "💨",
  hole: "🕳️",
  speech_balloon: "💬",
  eye_speech_bubble: "👁️‍🗨️",
  left_speech_bubble: "🗨️",
  right_anger_bubble: "🗯️",
  thought_balloon: "💭",
  zzz: "💤",

  //### People and Body ###

  // Hand Fingers Open
  wave: "👋",
  raised_back_of_hand: "🤚",
  raised_hand_with_fingers_splayed: "🖐️",
  hand: "✋",
  raised_hand: "✋",
  vulcan_salute: "🖖",

  // Hand Fingers Partial
  ok_hand: "👌",
  pinched_fingers: "🤌",
  pinching_hand: "🤏",
  v: "✌️",
  crossed_fingers: "🤞",
  love_you_gesture: "🤟",
  metal: "🤘",
  call_me_hand: "🤙",

  // Hand Single Finger
  point_left: "👈",
  point_right: "👉",
  point_up_2: "👆",
  middle_finger: "🖕",
  fu: "🖕",
  point_down: "👇",
  point_up: "☝️",

  // Hand Fingers Closed
  "+1": "👍",
  thumbsup: "👍",
  "-1": "👎",
  thumbsdown: "👎",
  fist: "✊",
  fist_raised: "✊",
  facepunch: "👊",
  fist_oncoming: "👊",
  punch: "👊",
  fist_left: "🤛",
  left_facing_fist: "🤛",
  fist_right: "🤜",
  right_facing_fist: "🤜",

  // Hands
  clap: "👏",
  raised_hands: "🙌",
  open_hands: "👐",
  palms_up_together: "🤲",
  handshake: "🤝",
  pray: "🙏",

  // Hand Prop
  writing_hand: "✍️",
  nail_care: "💅",
  selfie: "🤳",

  // Body Parts
  muscle: "💪",
  mechanical_arm: "🦾",
  mechanical_leg: "🦿",
  leg: "🦵",
  foot: "🦶",
  ear: "👂",
  ear_with_hearing_aid: "🦻",
  nose: "👃",
  brain: "🧠",
  anatomical_heart: "🫀",
  lungs: "🫁",
  tooth: "🦷",
  bone: "🦴",
  eyes: "👀",
  eye: "👁️",
  tongue: "👅",
  lips: "👄",

  // Person
  baby: "👶",
  child: "🧒",
  boy: "👦",
  girl: "👧",
  adult: "🧑",
  blond_haired_person: "👱",
  man: "👨",
  bearded_person: "🧔",
  man_beard: "🧔",
  woman_beard: "🧔‍",
  red_haired_man: "👨‍🦰",
  curly_haired_man: "👨‍🦱",
  white_haired_man: "👨‍🦳",
  bald_man: "👨‍🦲",
  woman: "👩",
  red_haired_woman: "👩‍🦰",
  person_red_hair: "🧑‍🦰",
  curly_haired_woman: "👩‍🦱",
  person_curly_hair: "🧑‍🦱",
  white_haired_woman: "👩‍🦳",
  person_white_hair: "🧑‍🦳",
  bald_woman: "👩‍🦲",
  person_bald: "🧑‍🦲",
  blond_haired_woman: "👱‍♀️",
  blond_woman: "👱‍♀️",
  blond_haired_man: "👱‍♂️",
  older_adult: "🧓",
  older_man: "👴",
  older_woman: "👵",

  // Person Gesture
  frowning_person: "🙍",
  frowning_man: "🙍‍♂️",
  frowning_woman: "🙍‍♀️",
  pouting_face: "🙎",
  pouting_man: "🙎‍♂️",
  pouting_woman: "🙎‍♀️",
  no_good: "🙅",
  ng_man: "🙅‍♂️",
  no_good_man: "🙅‍♂️",
  ng_woman: "🙅‍♀️",
  no_good_woman: "🙅‍♀️",
  ok_person: "🙆",
  ok_man: "🙆‍♂️",
  ok_woman: "🙆‍♀️",
  information_desk_person: "💁",
  tipping_hand_person: "💁",
  sassy_man: "💁‍♂️",
  tipping_hand_man: "💁‍♂️",
  sassy_woman: "💁‍♀️",
  tipping_hand_woman: "💁‍♀️",
  raising_hand: "🙋",
  raising_hand_man: "🙋‍♂️",
  raising_hand_woman: "🙋‍♀️",
  sassy_person: "💁",
  deaf_person: "🧏",
  deaf_man: "🧏‍♂️",
  deaf_woman: "🧏‍♀️",
  bow: "🙇",
  bowing_man: "🙇‍♂️",
  bowing_woman: "🙇‍♀️",
  facepalm: "🤦",
  man_facepalming: "🤦‍♂️",
  woman_facepalming: "🤦‍♀️",
  shrug: "🤷",
  man_shrugging: "🤷‍♂️",
  woman_shrugging: "🤷‍♀️",

  // Person Role
  health_worker: "🧑‍⚕️",
  man_health_worker: "👨‍⚕️",
  woman_health_worker: "👩‍⚕️",
  student: "🧑‍🎓",
  man_student: "👨‍🎓",
  woman_student: "👩‍🎓",
  teacher: "🧑‍🏫",
  man_teacher: "👨‍🏫",
  woman_teacher: "👩‍🏫",
  judge: "🧑‍⚖️",
  man_judge: "👨‍⚖️",
  woman_judge: "👩‍⚖️",
  farmer: "🧑‍🌾",
  man_farmer: "👨‍🌾",
  woman_farmer: "👩‍🌾",
  cook: "🧑‍🍳",
  man_cook: "👨‍🍳",
  woman_cook: "👩‍🍳",
  mechanic: "🧑‍🔧",
  man_mechanic: "👨‍🔧",
  woman_mechanic: "👩‍🔧",
  factory_worker: "🧑‍🏭",
  man_factory_worker: "👨‍🏭",
  woman_factory_worker: "👩‍🏭",
  office_worker: "🧑‍💼",
  man_office_worker: "👨‍💼",
  woman_office_worker: "👩‍💼",
  scientist: "🧑‍🔬",
  man_scientist: "👨‍🔬",
  woman_scientist: "👩‍🔬",
  technologist: "🧑‍💻",
  man_technologist: "👨‍💻",
  woman_technologist: "👩‍💻",
  singer: "🧑‍🎤",
  man_singer: "👨‍🎤",
  woman_singer: "👩‍🎤",
  artist: "🧑‍🎨",
  man_artist: "👨‍🎨",
  woman_artist: "👩‍🎨",
  pilot: "🧑‍✈️",
  man_pilot: "👨‍✈️",
  woman_pilot: "👩‍✈️",
  astronaut: "🧑‍🚀",
  man_astronaut: "👨‍🚀",
  woman_astronaut: "👩‍🚀",
  firefighter: "🧑‍🚒",
  man_firefighter: "👨‍🚒",
  woman_firefighter: "👩‍🚒",
  police_officer: "👮",
  policeman: "👮‍♂️",
  policewoman: "👮‍♀️",
  detective: "🕵️",
  male_detective: "🕵️‍♂️",
  female_detective: "🕵️‍♀️",
  guard: "💂",
  guardsman: "💂‍♂️",
  guardswoman: "💂‍♀️",
  ninja: "🥷",
  construction_worker: "👷",
  construction_worker_man: "👷‍♂️",
  construction_worker_woman: "👷‍♀️",
  prince: "🤴",
  princess: "👸",
  person_wearing_turban: "👳",
  person_with_turban: "👳",
  man_wearing_turban: "👳‍♂️",
  man_with_turban: "👳‍♂️",
  woman_wearing_turban: "👳‍♀️",
  woman_with_turban: "👳‍♀️",
  man_with_guai_pi_mao: "👲",
  man_with_chinese_cap: "👲",
  woman_with_headscarf: "🧕",
  person_in_tuxedo: "🤵",
  man_in_tuxedo: "🤵",
  woman_in_tuxedo: "🤵‍♀️",
  person_with_veil: "👰",
  man_with_veil: "👰",
  bride_with_veil: "👰",
  woman_with_veil: "👰",
  pregnant: "🤰",
  pregnant_woman: "🤰",
  breast_feeding: "🤱",
  woman_breast_feeding: "🤱",
  woman_feeding_baby: "🤱",
  man_feeding_baby: "👨‍🍼",
  person_feeding_baby: "🧑‍🍼",

  // Person Fantasy
  angel: "👼",
  santa: "🎅",
  claus: "🎅",
  mrs_claus: "🤶",
  mx_claus: "🧑‍🎄",
  superhero: "🦸",
  superhero_man: "🦸‍♂️",
  superhero_woman: "🦸‍♀️",
  supervillain: "🦹",
  supervillain_man: "🦹‍♂️",
  supervillain_woman: "🦹‍♀️",
  mage: "🧙",
  mage_man: "🧙‍♂️",
  mage_woman: "🧙‍♀️",
  fairy: "🧚",
  fairy_man: "🧚‍♂️",
  fairy_woman: "🧚‍♀️",

  man_in_business_suit_levitating: "🕴️",
  dancer: "💃",
  man_dancing: "🕺",
  people_with_bunny_ears: "👯",
  men_with_bunny_ears_partying: "👯‍♂️",
  women_with_bunny_ears_partying: "👯‍♀️",
  person_in_steamy_room: "🧖",
  man_in_steamy_room: "🧖‍♂️",
  woman_in_steamy_room: "🧖‍♀️",
  person_climbing: "🧗",
  man_climbing: "🧗‍♂️",
  woman_climbing: "🧗‍♀️",
  person_fencing: "🤺",
  horse_racing: "🏇",
  skier: "⛷️",
  snowboarder: "🏂",
  person_golfing: "🏌️",
  man_golfing: "🏌️‍♂️",
  woman_golfing: "🏌️‍♀️",
  person_surfing: "🏄",
  man_surfing: "🏄‍♂️",
  woman_surfing: "🏄‍♀️",
  person_rowing_boat: "🚣",
  man_rowing_boat: "🚣‍♂️",
  woman_rowing_boat: "🚣‍♀️",
  person_swimming: "🏊",
  man_swimming: "🏊‍♂️",
  woman_swimming: "🏊‍♀️",
  person_bouncing_ball: "⛹️",
  man_bouncing_ball: "⛹️‍♂️",
  woman_bouncing_ball: "⛹️‍♀️",
  person_lifting_weights: "🏋️",
  man_lifting_weights: "🏋️‍♂️",
  woman_lifting_weights: "🏋️‍♀️",
  person_biking: "🚴",
  man_biking: "🚴‍♂️",
  woman_biking: "🚴‍♀️",
  person_mountain_biking: "🚵",
  man_mountain_biking: "🚵‍♂️",
  woman_mountain_biking: "🚵‍♀️",
  person_cartwheeling: "🤸",
  man_cartwheeling: "🤸‍♂️",
  woman_cartwheeling: "🤸‍♀️",
  people_wrestling: "🤼",
  men_wrestling: "🤼‍♂️",
  women_wrestling: "🤼‍♀️",
  person_playing_water_polo: "🤽",
  man_playing_water_polo: "🤽‍♂️",
  woman_playing_water_polo: "🤽‍♀️",
  person_playing_handball: "🤾",
  man_playing_handball: "🤾‍♂️",
  woman_playing_handball: "🤾‍♀️",
  person_juggling: "🤹",
  man_juggling: "🤹‍♂️",
  woman_juggling: "🤹‍♀️",
  person_in_lotus_position: "🧘",
  man_in_lotus_position: "🧘‍♂️",
  woman_in_lotus_position: "🧘‍♀️",
  person_taking_bath: "🛀",
  person_in_bed: "🛌",
  baby_angel: "👼",
  breastfeeding: "🤱",
  elf: "🧝",
  genie: "🧞",
  man_elf: "🧝‍♂️",
  man_fairy: "🧚‍♂️",
  man_genie: "🧞‍♂️",
  man_mage: "🧙‍♂️",
  man_superhero: "🦸‍♂️",
  man_supervillain: "🦹‍♂️",
  man_vampire: "🧛‍♂️",
  man_zombie: "🧟‍♂️",
  mermaid: "🧜‍♀️",
  merman: "🧜‍♂️",
  merperson: "🧜",
  vampire: "🧛",
  woman_elf: "🧝‍♀️",
  woman_fairy: "🧚‍♀️",
  woman_genie: "🧞‍♀️",
  woman_mage: "🧙‍♀️",
  woman_superhero: "🦸‍♀️",
  woman_supervillain: "🦹‍♀️",
  woman_vampire: "🧛‍♀️",
  woman_zombie: "🧟‍♀️",
  zombie: "🧟",
};
